# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "roboxes/debian10"

  config.vm.synced_folder "./", "/vagrant/", create: true


  config.vm.define "control" do |machine|
    machine.vm.hostname = "control"
    machine.vm.network "private_network", ip: "192.168.50.10"
  end

  config.vm.define "node01" do |machine|
    machine.vm.hostname = "node01"
    machine.vm.network "private_network", ip: "192.168.50.11"
  end

  config.vm.define "node02" do |machine|
    machine.vm.hostname = "node02"
    machine.vm.network "private_network", ip: "192.168.50.12"
  end

  config.vm.define "node03" do |machine|
    machine.vm.hostname = "node03"
    machine.vm.network "private_network", ip: "192.168.50.13"
  end

  config.vm.provision "shell", inline: <<-SHELL
    echo "" >> /etc/hosts
    echo "192.168.50.10 control" >> /etc/hosts
    echo "192.168.50.11 node01" >> /etc/hosts
    echo "192.168.50.12 node02" >> /etc/hosts
    echo "192.168.50.13 node03" >> /etc/hosts
    sed -i -E 's/^127.0.0.1\s+debian10.localdomain//' /etc/hosts
    sed -i -E 's/^127.0.[0-9]+.[0-9]+\s+(control|node[0-9]+).*$//' /etc/hosts
  SHELL

end

