chema@Chema-PC:~/pruebaskube/minikube$ cat Vagrantfile 
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "roboxes/debian10"
  config.vm.box_check_update = false
  config.vm.synced_folder "./", "/vagrant/", create: true
  config.vm.hostname = "minikube"
end

